package com.houwei.guaishang.database.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.houwei.guaishang.database.entity.HomeTopicCacheData;

import com.houwei.guaishang.database.entity.HomeTopicCacheDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeTopicCacheDataDaoConfig;

    private final HomeTopicCacheDataDao homeTopicCacheDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeTopicCacheDataDaoConfig = daoConfigMap.get(HomeTopicCacheDataDao.class).clone();
        homeTopicCacheDataDaoConfig.initIdentityScope(type);

        homeTopicCacheDataDao = new HomeTopicCacheDataDao(homeTopicCacheDataDaoConfig, this);

        registerDao(HomeTopicCacheData.class, homeTopicCacheDataDao);
    }
    
    public void clear() {
        homeTopicCacheDataDaoConfig.clearIdentityScope();
    }

    public HomeTopicCacheDataDao getHomeTopicCacheDataDao() {
        return homeTopicCacheDataDao;
    }

}
