package com.houwei.guaishang.database.entity;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.houwei.guaishang.database.entity.HomeTopicCacheData;
import com.houwei.guaishang.database.entity.ChatInfoData;

import com.houwei.guaishang.database.entity.HomeTopicCacheDataDao;
import com.houwei.guaishang.database.entity.ChatInfoDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig homeTopicCacheDataDaoConfig;
    private final DaoConfig chatInfoDataDaoConfig;

    private final HomeTopicCacheDataDao homeTopicCacheDataDao;
    private final ChatInfoDataDao chatInfoDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        homeTopicCacheDataDaoConfig = daoConfigMap.get(HomeTopicCacheDataDao.class).clone();
        homeTopicCacheDataDaoConfig.initIdentityScope(type);

        chatInfoDataDaoConfig = daoConfigMap.get(ChatInfoDataDao.class).clone();
        chatInfoDataDaoConfig.initIdentityScope(type);

        homeTopicCacheDataDao = new HomeTopicCacheDataDao(homeTopicCacheDataDaoConfig, this);
        chatInfoDataDao = new ChatInfoDataDao(chatInfoDataDaoConfig, this);

        registerDao(HomeTopicCacheData.class, homeTopicCacheDataDao);
        registerDao(ChatInfoData.class, chatInfoDataDao);
    }
    
    public void clear() {
        homeTopicCacheDataDaoConfig.clearIdentityScope();
        chatInfoDataDaoConfig.clearIdentityScope();
    }

    public HomeTopicCacheDataDao getHomeTopicCacheDataDao() {
        return homeTopicCacheDataDao;
    }

    public ChatInfoDataDao getChatInfoDataDao() {
        return chatInfoDataDao;
    }

}
